name: gofit_fitness
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # This range is generally good for Dart 3.x

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  intl: ^0.19.0
  youtube_player_flutter: ^8.1.2
  # FIX: Downgraded flutter_radar_chart as suggested by the error message.
  flutter_radar_chart: ^0.2.1 # <--- CHANGE THIS LINE TO ^0.2.1

flutter:
  uses-material-design: true